Traceback (most recent call last):
  File "/home/ubuntu/nautobot-dev/nautobot/venv/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/nautobot-dev/nautobot/nautobot/core/cli/__init__.py", line 292, in main
    load_settings(args.config_path)
  File "/home/ubuntu/nautobot-dev/nautobot/nautobot/core/cli/__init__.py", line 131, in load_settings
    raise FileNotFoundError(
FileNotFoundError: Configuration file not found at /home/ubuntu/.nautobot/nautobot_config.py - Please provide a valid --config-path path, or use 'nautobot-server init' to create a new configuration.
 path, or use 'nautobot-server init' to create a new configuration.
